---
- name: download go archive
  get_url:
    url: https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz

- name: unarchive archive
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
  become: true

- name: create go home directory
  file:
    path: ~/go
    state: directory
    mode: 0755

- name: create go bin directory
  file:
    path: ~/go/bin
    state: directory
    mode: 0755

- name: add GOROOT to PATH
  lineinfile:
    path: "{{ item }}"
    state: present
    line: 'PATH=$PATH:/usr/local/go/bin'
  with_items:
    - ~/.bash_profile
    - ~/.bashrc

- name: set GOPATH in profile
  lineinfile:
    path: "{{ item }}"
    state: present
    line: 'export GOPATH=~/go'
  with_items:
    - ~/.bash_profile
    - ~/.bashrc

- name: set GOBIN in profile
  lineinfile:
    path: "{{ item }}"
    state: present
    line: 'export GOBIN=~/go/bin'
  with_items:
    - ~/.bash_profile
    - ~/.bashrc

- name: add GOPATH to PATH in profile
  lineinfile:
    path: "{{ item }}"
    state: present
    line: 'export PATH="$PATH:$GOPATH/bin"'
  with_items:
    - ~/.bash_profile
    - ~/.bashrc

- name: install dep
  shell: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
